plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  
minimal_mistakes_skin: "default"
remote_theme: "mmistakes/minimal-mistakes@4.17.2"

locale: "en-US"
title: "WebLaF Style Editor"
title_separator: "-"
name: "Nikita Shtengauer"
description: "Tool for creating amazing styles."

url: "https://husker-dev.github.io"
baseurl: "/weblaf-style-editor"

repository: "husker-dev/weblaf-style-editor"
teaser: "/assets/iamges/bakground.png"
logo: "/assets/iamges/wlogo.png"
masthead_title: "WebLaF Style Editor"
author:
  name: "Nikita Shtengauer"
  avatar: "/assets/iamges/logo.png"
  bio: "I am just Java developer"
  location: "Russia, Karelia, Kostomuksha"
  email: "redfancoestar@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:redfancoestar@gmail.com
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/husker-dev"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/shtengauer_nikita/"
